### ISSUE TITLE
AppArmor Policy Error

### ISSUE THREAD

**Issue by fweth** [canonical/firmware-updater#204] opened 2023-10-08 17:53 UTC
I got this error on Ubuntu 23.10:

![](https://i.imgur.com/FFoDYUP.png)

Seems to be only related to auto reboot, after manual reboot, it seems to have updated the firmware just fine.

**Comment by d-loose** [comment] 2023-10-09 09:48
Duplicate of #164 - will take care of that soon

**Closed by d-loose** 2023-10-09 09:48 UTC
